"""``mechlint`` command line.

One subcommand per core function, plus ``check`` which runs them all and sets
the exit code. Inspect subcommands never write; the only thing mechlint ever
writes is a *generated* ``inertials.xacro`` that the description includes.

Exit codes:
    0   everything checked passed
    1   a check failed (this is what turns a CI run red)
    2   usage error, or a subcommand that is not implemented yet
"""

from __future__ import annotations

from pathlib import Path
from typing import Annotated, NoReturn

import typer

from mechlint import __version__
from mechlint.core import report as render
from mechlint.core import units
from mechlint.core.actuators import ActuatorDatabase, load_database
from mechlint.core.checks import check_urdf
from mechlint.core.config import MechlintConfig
from mechlint.core.inertia import compute_inertia, inertials_xacro
from mechlint.core.report import FullReport
from mechlint.core.torque import DEFAULT_SAMPLES, torque_budget
from mechlint.core.urdf import DescriptionError, PackageResolver, RobotModel

app = typer.Typer(
    name="mechlint",
    help="Lint and CI for robot mechanics: mass, inertia and joint torque from CAD + URDF, "
    "checked against actuator and printing limits.",
    no_args_is_help=True,
    add_completion=False,
)

DEFAULT_CONFIG = "mechlint.yaml"
GENERATED_MARKER = "Generated by mechlint"

#: Which milestone each unbuilt subcommand lands in. Printed by the stubs so
#: nobody has to read the plan to find out whether a command is missing or
#: just unbuilt.
_MILESTONE = {"drift": "M4", "render": "M4"}


# --------------------------------------------------------------------------- shared options

Description = Annotated[
    Path | None,
    typer.Argument(
        metavar="[DESCRIPTION]",
        help="URDF or xacro to read. Defaults to robot.description from the config.",
    ),
]
Config = Annotated[
    Path | None,
    typer.Option("--config", "-c", help=f"Project config. Defaults to ./{DEFAULT_CONFIG}."),
]
ModelScale = Annotated[
    str | None,
    typer.Option(
        "--model-scale",
        "-s",
        help="Metres per URDF unit, or a unit name such as 'dm'. Overrides the config.",
    ),
]
PackagePaths = Annotated[
    list[str] | None,
    typer.Option(
        "--package-path",
        "-p",
        metavar="PKG=DIR",
        help="Resolve package:// without a sourced ROS shell. Repeatable.",
    ),
]
XacroArgs = Annotated[
    list[str] | None,
    typer.Option("--xacro-arg", "-a", metavar="NAME=VALUE", help="Passed to xacro. Repeatable."),
]
Format = Annotated[
    str,
    typer.Option("--format", "-f", help="Output format: table, json or markdown."),
]
ActuatorDb = Annotated[
    Path | None,
    typer.Option("--actuator-db", help="Extra actuator YAML, merged over the bundled table."),
]
Voltage = Annotated[
    float | None,
    typer.Option("--voltage", "-V", help="Supply voltage. Overrides actuators.voltage."),
]
Payloads = Annotated[
    list[float] | None,
    typer.Option(
        "--payload",
        "-P",
        metavar="GRAMS",
        help="Payload at the tip, in grams. Repeatable: one column per value. "
        "Overrides scenario.payload_g.",
    ),
]
Assignments = Annotated[
    list[str] | None,
    typer.Option(
        "--actuator",
        metavar="JOINT=KEY",
        help="Assign an actuator to a joint for this run only. Repeatable; "
        "JOINT= with nothing after it un-assigns.",
    ),
]
Mount = Annotated[
    str | None,
    typer.Option(
        "--mount",
        help="table, ceiling, or 'gx,gy,gz'. Overrides both the config and the model's "
        "own world-to-base rotation, for what-if questions.",
    ),
]
Samples = Annotated[
    int,
    typer.Option("--samples", help="Poses to search. The joint-limit corners are always in."),
]


def _fail(message: str, hint: str = "") -> NoReturn:
    typer.secho(f"mechlint: {message}", err=True, fg=typer.colors.RED)
    if hint:
        typer.secho(f"  hint: {hint}", err=True)
    raise typer.Exit(code=2)


def _pairs(values: list[str] | None, option: str) -> dict[str, str]:
    parsed = {}
    for value in values or []:
        name, sep, rest = value.partition("=")
        if not sep or not name:
            _fail(f"{option} wants NAME=VALUE, got {value!r}")
        parsed[name] = rest
    return parsed


def _load_config(path: Path | None) -> MechlintConfig | None:
    """The project config: the one named, else ``./mechlint.yaml`` if it exists."""
    if path is None:
        default = Path(DEFAULT_CONFIG)
        if not default.is_file():
            return None
        path = default
    try:
        return MechlintConfig.from_yaml(path)
    except Exception as error:
        _fail(f"{path}: {error}")


def _load(
    description: Path | None,
    config_path: Path | None,
    model_scale: str | None,
    package_paths: list[str] | None,
    xacro_args: list[str] | None,
) -> tuple[MechlintConfig | None, RobotModel]:
    """Everything every command needs, with CLI arguments winning over the config."""
    config = _load_config(config_path)

    if description is None:
        if config is None:
            _fail(
                "no description given and no config found",
                f"pass a URDF or xacro, or run where a {DEFAULT_CONFIG} lives.",
            )
        description = config.description_path

    packages: dict[str, Path] = {}
    if config is not None:
        packages = {name: config.resolve(path) for name, path in config.robot.package_paths.items()}
    packages.update(
        {name: Path(path) for name, path in _pairs(package_paths, "--package-path").items()}
    )

    arguments = dict(config.robot.xacro_args) if config is not None else {}
    arguments.update(_pairs(xacro_args, "--xacro-arg"))

    raw_scale = (
        model_scale
        if model_scale is not None
        else (config.robot.model_scale if config is not None else 1.0)
    )
    try:
        scale = units.resolve_scale(raw_scale)
    except ValueError as error:
        _fail(str(error))

    try:
        model = RobotModel.load(
            description,
            xacro_args=arguments,
            resolver=PackageResolver(packages),
            model_scale=scale,
        )
    except DescriptionError as error:
        _fail(error.message, error.hint)
    return config, model


def _actuator_database(path: Path | None, config: MechlintConfig | None = None) -> ActuatorDatabase:
    """The bundled table, extended by the project's own YAML, then by ``--actuator-db``."""
    source = path if path is not None else (config.actuator_db_path if config else None)
    try:
        return load_database(source)
    except Exception as error:
        _fail(f"{source}: {error}")


def _mount_value(text: str | None) -> object | None:
    """``--mount`` as either a name or a vector. A comma is what tells the two apart."""
    if text is None:
        return None
    if "," not in text:
        return text
    try:
        values = [float(part) for part in text.split(",")]
    except ValueError:
        _fail(f"--mount {text!r} is neither a name nor gx,gy,gz")
    if len(values) != 3:
        _fail(f"--mount wants three numbers, got {len(values)}")
    return tuple(values)


def _assignments(values: list[str] | None) -> dict[str, str | None]:
    """``JOINT=KEY`` pairs, where an empty value means "no actuator on this joint"."""
    return {joint: (key or None) for joint, key in _pairs(values, "--actuator").items()}


def _emit(report: object, output_format: str, table: str, markdown: str) -> None:
    if output_format == "json":
        typer.echo(render.to_json(report))  # type: ignore[arg-type]
    elif output_format in ("markdown", "md"):
        typer.echo(markdown)
    elif output_format == "table":
        typer.echo(table)
    else:
        _fail(f"unknown format {output_format!r}", "use table, json or markdown.")


def _version_callback(value: bool) -> None:
    if value:
        typer.echo(f"mechlint {__version__}")
        raise typer.Exit()


@app.callback()
def main(
    version: Annotated[
        bool,
        typer.Option("--version", callback=_version_callback, is_eager=True, help="Show version."),
    ] = False,
) -> None:
    """Robot mechanics, checked."""


# --------------------------------------------------------------------------- commands


@app.command()
def inertia(
    description: Description = None,
    config: Config = None,
    model_scale: ModelScale = None,
    package_path: PackagePaths = None,
    xacro_arg: XacroArgs = None,
    output_format: Format = "table",
    write: Annotated[
        Path | None,
        typer.Option(
            "--write",
            "-w",
            help="Write inertials.xacro here. A directory gets inertials.xacro inside it.",
        ),
    ] = None,
    force: Annotated[
        bool, typer.Option("--force", help="Overwrite a file mechlint did not generate.")
    ] = False,
) -> None:
    """Mass, centre of mass and inertia tensor per link, in the link frame."""
    project, model = _load(description, config, model_scale, package_path, xacro_arg)
    result = compute_inertia(model, project)

    if write is not None:
        target = write / "inertials.xacro" if write.is_dir() else write
        if target.exists() and not force and GENERATED_MARKER not in target.read_text():
            _fail(
                f"{target} was not generated by mechlint",
                "mechlint only overwrites its own output. Pass --force, or write elsewhere.",
            )
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(inertials_xacro(result))
        typer.secho(
            f"wrote {len(result.writable_links)} inertials to {target}", err=True, fg="green"
        )

    _emit(result, output_format, render.render_inertia(result), render.inertia_markdown(result))


@app.command("urdf-check")
def urdf_check(
    description: Description = None,
    config: Config = None,
    model_scale: ModelScale = None,
    package_path: PackagePaths = None,
    xacro_arg: XacroArgs = None,
    output_format: Format = "table",
) -> None:
    """Physical sanity of the URDF: units, tensors, masses, meshes (U0xx, M0xx)."""
    project, model = _load(description, config, model_scale, package_path, xacro_arg)
    result = check_urdf(model, project)
    _emit(result, output_format, render.render_checks(result), render.checks_markdown(result))
    raise typer.Exit(code=0 if result.ok else 1)


@app.command()
def torque(
    description: Description = None,
    config: Config = None,
    model_scale: ModelScale = None,
    package_path: PackagePaths = None,
    xacro_arg: XacroArgs = None,
    output_format: Format = "table",
    payload: Payloads = None,
    voltage: Voltage = None,
    actuator: Assignments = None,
    mount: Mount = None,
    actuator_db: ActuatorDb = None,
    samples: Samples = DEFAULT_SAMPLES,
) -> None:
    """Worst-case static joint torque, and the margin against the assigned actuator (T001)."""
    project, model = _load(description, config, model_scale, package_path, xacro_arg)
    result = torque_budget(
        model,
        project,
        actuators=_actuator_database(actuator_db, project),
        payloads_g=payload or None,
        voltage=voltage,
        assignments=_assignments(actuator),
        mount=_mount_value(mount),
        samples=samples,
    )
    _emit(result, output_format, render.render_torque(result), render.torque_markdown(result))
    raise typer.Exit(code=0 if result.ok else 1)


@app.command()
def actuators(
    key: Annotated[
        str | None,
        typer.Argument(metavar="[ACTUATOR]", help="Show one entry in full, with its source."),
    ] = None,
    min_torque: Annotated[
        float | None,
        typer.Option("--min-torque", "-t", metavar="NM", help="Only entries that reach this."),
    ] = None,
    max_mass: Annotated[
        float | None,
        typer.Option("--max-mass", "-m", metavar="GRAMS", help="Only entries no heavier."),
    ] = None,
    kind: Annotated[
        str | None,
        typer.Option("--kind", help="hobby_servo, smart_servo or stepper."),
    ] = None,
    voltage: Voltage = None,
    config: Config = None,
    actuator_db: ActuatorDb = None,
    output_format: Format = "table",
) -> None:
    """The actuator database: what each motor delivers, and the source it was read from."""
    # This command needs no robot, but it still reads the config: a project that ships its
    # own actuator YAML should see those entries listed here too, not only inside `torque`.
    database = _actuator_database(actuator_db, _load_config(config))

    if key is not None:
        try:
            entry = database[key]
        except KeyError as error:
            _fail(str(error))
        _emit(
            entry,
            output_format,
            render.actuator_detail(entry),
            render.actuator_detail_markdown(entry),
        )
        return

    try:
        found = database.matching(
            min_torque_Nm=min_torque,
            voltage=voltage,
            max_mass_g=max_mass,
            kind=kind,  # type: ignore[arg-type]
        )
    except ValueError as error:
        _fail(str(error))
    _emit(
        found,
        output_format,
        render.render_actuators(found, voltage=voltage),
        render.actuators_markdown(found, voltage=voltage),
    )


@app.command()
def drift() -> None:
    """Disagreements between the CAD and the URDF that describes it (D0xx)."""
    _not_implemented("drift")


@app.command("render")
def render_png() -> None:
    """Multi-view PNG of a pose, with labelled joint frames. For the human, not for numbers."""
    _not_implemented("render")


@app.command()
def check(
    description: Description = None,
    config: Config = None,
    model_scale: ModelScale = None,
    package_path: PackagePaths = None,
    xacro_arg: XacroArgs = None,
    output_format: Format = "table",
    payload: Payloads = None,
    voltage: Voltage = None,
    mount: Mount = None,
    actuator_db: ActuatorDb = None,
    samples: Samples = DEFAULT_SAMPLES,
) -> None:
    """Run every check and exit non-zero if any fails. This is the CI entry point."""
    project, model = _load(description, config, model_scale, package_path, xacro_arg)
    database = _actuator_database(actuator_db, project)
    result = FullReport(
        checks=check_urdf(model, project, actuators=database),
        torque=torque_budget(
            model,
            project,
            actuators=database,
            payloads_g=payload or None,
            voltage=voltage,
            mount=_mount_value(mount),
            samples=samples,
        ),
    )
    _emit(result, output_format, render.render_full(result), render.full_markdown(result))
    raise typer.Exit(code=0 if result.ok else 1)


def _not_implemented(command: str) -> None:
    typer.secho(
        f"mechlint {command}: not implemented yet (planned for {_MILESTONE[command]}).",
        err=True,
        fg=typer.colors.YELLOW,
    )
    raise typer.Exit(code=2)


if __name__ == "__main__":
    app()
